site_name: Magellan
theme: cyborg
pages:
  - Home : index.md
  - Components: components.md
  - Communication: comm.md
  #  - Architecture: arch.md  # disabled until complete
  # - Testing : test.md  # disabled until complete
  - Demo: demo.md
  - Guides: guide.md
